"""Tests for the crypto order-flow-imbalance family. The load-bearing
ones, in the order the build's own priorities put them:

  * test_orthogonalization_kills_a_pure_reversal_signal and
    test_orthogonalization_preserves_a_genuine_order_flow_signal — the
    pair that proves the family's central claim. Two synthetic worlds,
    generated by the SAME code with one difference: in the first, order
    flow carries nothing but the same-period return (so any "edge" is
    short-term reversal wearing an order-flow costume); in the second it
    also carries an independent component that genuinely predicts the next
    period. Orthogonalization must destroy the first and keep the second.
    Both run the real end-to-end pipeline, not a stub.
  * test_orthogonalized_signal_ignores_all_future_data — every panel row
    after a formation is overwritten with garbage and the signal at that
    formation must be bit-identical, which is the no-look-ahead property
    the expanding-window estimator exists to provide.
  * test_order_flow_log_difference_hand_computed and
    test_standardization_is_scale_only_not_a_z_score — the formula pinned
    against numbers worked out by hand, including the one place it is
    easiest to be wrong (the source standardizes by sigma alone and does
    NOT subtract a mean).

Everything uses calendar-day indexes: crypto has no weekends, and a bdate
fixture would test the wrong calendar (the sibling crypto test files' own
convention)."""

import itertools
import math
from datetime import date

import numpy as np
import pandas as pd
import pytest

from app.services.market_data.binance_futures_provider import KLINE_COLUMNS
from app.services.research_lab.cross_sectional_ofi import (
    BINANCE_TAKER_FEE_BPS,
    MIN_ORTHO_REGRESSION_OBS,
    OFI_COST_BPS,
    OFI_FAMILY_KEY,
    OFI_HORIZON_DAYS,
    OFI_N_TRIALS,
    OFI_RANK_FRACTION,
    OFI_SIGNAL_VARIANTS,
    OFI_STANDARDIZATION_WINDOW,
    OfiConfig,
    OfiPanels,
    OfiScreeningSummary,
    OfiSpec,
    OfiSpecResult,
    _build_summary_text,
    build_ofi_family,
    build_ofi_signals,
    expanding_orthogonalize,
    formation_grid,
    order_flow_log_difference,
    run_ofi_backtest,
    screen_ofi_family,
    standardize_order_flow,
)
from app.services.research_lab.deflated_sharpe import compute_deflated_sharpe
from app.services.research_lab.metrics import sharpe_ratio

# 40 coins so a quintile leg (8) clears OFI_MIN_NAMES_PER_LEG (5) and the
# two legs stay disjoint — the same gate the real universe has to pass.
SYMBOLS = [f"C{i:02d}USDT" for i in range(40)]


# --- synthetic-world construction -------------------------------------------


def _panels_from_flows(
    order_flow: pd.DataFrame,
    close: pd.DataFrame,
    total_quote: float = 1e9,
) -> OfiPanels:
    """Inverts the source's flow definition to build a panel that HAS a
    prescribed order flow: given a target of = log(buy) - log(sell) and a
    total turnover V, buy = V*e^of/(1+e^of) and sell = V/(1+e^of). So the
    test controls the economics directly and still exercises the real
    log-difference code path rather than injecting a signal behind it."""
    ratio = np.exp(order_flow)
    buy = total_quote * ratio / (1.0 + ratio)
    sell = total_quote / (1.0 + ratio)
    volume = pd.DataFrame(total_quote, index=close.index, columns=close.columns)
    return OfiPanels(
        close=close,
        quote_volume=volume,
        buy_quote=buy,
        sell_quote=sell,
        trade_count=pd.DataFrame(10_000.0, index=close.index, columns=close.columns),
        coverage={},
        symbols_missing=[],
    )


def _build_world(
    *,
    flow_carries_genuine_info: bool,
    n_days: int = 900,
    seed: int = 20260829,
) -> OfiPanels:
    """Two worlds from one generator, differing only in `flow_carries_genuine_info`.

    In BOTH worlds returns mean-revert hard (r_{t+1} has a -0.6 loading on
    r_t: strong short-term reversal) and order flow is dominated by a term
    proportional to the SAME-period return, which is exactly the
    contamination the source's footnote-12 orthogonalization exists to
    remove.

    The ONLY difference: when flow_carries_genuine_info is True, order flow
    also contains an independent component g that genuinely predicts the
    next period's return with a POSITIVE sign — the source's "permanent
    effect". When False, g is pure noise that predicts nothing, so every
    bit of predictive content in the raw flow is the reversal term."""
    rng = np.random.default_rng(seed)
    index = pd.date_range("2020-01-01", periods=n_days, freq="D")
    shape = (n_days, len(SYMBOLS))

    g = rng.normal(0.0, 1.0, shape)  # the independent "permanent" component
    shock = rng.normal(0.0, 0.03, shape)

    r = np.zeros(shape)
    r[0] = shock[0]
    for t in range(1, n_days):
        r[t] = -0.6 * r[t - 1] + shock[t]
        if flow_carries_genuine_info:
            r[t] += 0.05 * g[t - 1]

    # Order flow is dominated by the same-period return (the transitory,
    # reversal-correlated part) plus the independent component.
    of = 40.0 * r + 1.5 * g

    close = pd.DataFrame(
        100.0 * np.cumprod(1.0 + r, axis=0), index=index, columns=SYMBOLS
    )
    return _panels_from_flows(
        pd.DataFrame(of, index=index, columns=SYMBOLS), close
    )


def _sharpe_of(panels: OfiPanels, variant: str, horizon: int = 1) -> float:
    spec = OfiSpec(
        pattern_id=f"t_{variant}_h{horizon}", signal_variant=variant, horizon_days=horizon
    )
    config = OfiConfig(cost_bps=0.0, formation_start=date(2020, 1, 1))
    bt = run_ofi_backtest(panels, spec, config)
    assert len(bt.daily_returns) > 200, "synthetic replay produced too few days to judge"
    return sharpe_ratio(bt.daily_returns, periods_per_year=365.0)


# --- THE central pair --------------------------------------------------------


def test_orthogonalization_kills_a_pure_reversal_signal():
    """World where order flow carries NO independent information: all of
    its apparent predictive power is the same-period return, i.e. short-term
    reversal. The RAW flow must therefore look strongly predictive (with the
    sign reversal implies — high flow means a high past return means a LOW
    next return, so a long-high-flow book loses badly), and orthogonalizing
    must collapse that to nothing."""
    panels = _build_world(flow_carries_genuine_info=False)

    raw = _sharpe_of(panels, "raw")
    ortho = _sharpe_of(panels, "ortho")

    assert raw < -2.0, (
        f"raw flow should inherit the reversal effect strongly, got Sharpe {raw:.3f} — "
        "the fixture is not producing the contamination the test is about"
    )
    assert abs(ortho) < 0.75, (
        f"orthogonalized flow should retain NOTHING in a world where flow carries no "
        f"independent information, but scored Sharpe {ortho:.3f}"
    )
    assert abs(ortho) < abs(raw) / 3.0, (
        f"orthogonalization barely dented the reversal signal: |{ortho:.3f}| vs |{raw:.3f}|"
    )


def test_orthogonalization_preserves_a_genuine_order_flow_signal():
    """Same generator, same reversal contamination, same magnitudes — the
    one change is that order flow now also carries an independent component
    that really does predict the next period. The orthogonalized signal must
    survive and must BEAT the raw one, because the raw one is still dragged
    the wrong way by the reversal term it never removed."""
    panels = _build_world(flow_carries_genuine_info=True)

    raw = _sharpe_of(panels, "raw")
    ortho = _sharpe_of(panels, "ortho")

    assert ortho > 2.0, (
        f"a genuine order-flow effect must survive orthogonalization, got Sharpe {ortho:.3f}"
    )
    assert ortho > raw, (
        f"orthogonalized ({ortho:.3f}) should beat raw ({raw:.3f}) when the raw signal is "
        "still contaminated by a reversal term pointing the other way"
    )


def test_the_two_worlds_differ_only_in_the_genuine_component():
    """Guards the pair above from a fixture bug: the two worlds must share
    an identical reversal structure, so the difference in the orthogonalized
    result cannot come from anything else. The RAW Sharpe stays strongly
    negative in both (same contamination); only the ORTHO Sharpe moves."""
    no_info = _build_world(flow_carries_genuine_info=False)
    with_info = _build_world(flow_carries_genuine_info=True)

    assert _sharpe_of(no_info, "raw") < -2.0
    assert _sharpe_of(with_info, "raw") < -2.0
    assert _sharpe_of(no_info, "ortho") < 0.75 < _sharpe_of(with_info, "ortho")


# --- no look-ahead -----------------------------------------------------------


def test_orthogonalized_signal_ignores_all_future_data():
    """The expanding-window estimator's whole purpose. Overwrite EVERY panel
    row after a chosen formation with garbage — prices, both signed volume
    halves — and the signal at that formation must be bit-identical, for the
    raw and the orthogonalized variant alike."""
    # 900 days so the weekly grid has ~128 points: the standardization needs
    # 30 and the expanding regression 30 more, so an orthogonalized signal
    # does not exist before grid point ~59. Choosing a formation inside the
    # warm-up would make this test compare NaN to NaN and pass vacuously.
    panels = _build_world(flow_carries_genuine_info=True, n_days=900)
    horizon = 7
    before = build_ofi_signals(panels, horizon)

    rows = formation_grid(panels.close.index, horizon)
    k = len(rows) * 3 // 4
    cut = rows[k]
    assert before.ortho.iloc[k].notna().any(), (
        "fixture chose a formation inside the signal warm-up — nothing to compare"
    )

    rng = np.random.default_rng(7)
    mutated = OfiPanels(
        close=panels.close.copy(),
        quote_volume=panels.quote_volume.copy(),
        buy_quote=panels.buy_quote.copy(),
        sell_quote=panels.sell_quote.copy(),
        trade_count=panels.trade_count.copy(),
        coverage={},
        symbols_missing=[],
    )
    tail = slice(cut + 1, None)
    shape = mutated.close.iloc[tail].shape
    mutated.close.iloc[tail] = rng.uniform(1.0, 500.0, shape)
    mutated.buy_quote.iloc[tail] = rng.uniform(1e6, 9e8, shape)
    mutated.sell_quote.iloc[tail] = rng.uniform(1e6, 9e8, shape)

    after = build_ofi_signals(mutated, horizon)

    for name, b, a in (
        ("raw", before.raw, after.raw),
        ("ortho", before.ortho, after.ortho),
        ("period_return", before.period_return, after.period_return),
    ):
        pd.testing.assert_series_equal(
            b.iloc[k], a.iloc[k], check_names=False,
            obj=f"{name} signal at formation {before.raw.index[k].date()}",
        )
        # and every earlier formation too, not just the boundary one
        pd.testing.assert_frame_equal(
            b.iloc[: k + 1], a.iloc[: k + 1], obj=f"{name} signals up to the formation"
        )

    assert not before.ortho.iloc[k].isna().all(), "fixture produced an all-NaN signal to compare"


def test_mutating_the_formation_row_itself_does_change_the_signal():
    """The other half of the look-ahead test: data AT the formation is known
    and must be used. Without this, a signal that ignored everything would
    pass the test above."""
    panels = _build_world(flow_carries_genuine_info=True, n_days=900)
    horizon = 7
    before = build_ofi_signals(panels, horizon)
    rows = formation_grid(panels.close.index, horizon)
    k = len(rows) * 3 // 4
    assert before.raw.iloc[k].notna().any(), "fixture chose a formation inside the warm-up"

    mutated = OfiPanels(
        close=panels.close.copy(),
        quote_volume=panels.quote_volume.copy(),
        buy_quote=panels.buy_quote.copy(),
        sell_quote=panels.sell_quote.copy(),
        trade_count=panels.trade_count.copy(),
        coverage={},
        symbols_missing=[],
    )
    mutated.buy_quote.iloc[rows[k]] *= 5.0

    after = build_ofi_signals(mutated, horizon)
    assert not np.allclose(
        before.raw.iloc[k].to_numpy(), after.raw.iloc[k].to_numpy(), equal_nan=True
    ), "formation-row flow is settled, known data and must move the signal"


def test_expanding_orthogonalize_coefficients_use_only_past_and_present():
    """Unit-level companion to the panel test: the residual at t equals the
    residual of an OLS fitted by hand on rows 0..t ONLY."""
    rng = np.random.default_rng(11)
    n = 200
    x = pd.DataFrame({"A": rng.normal(size=n)})
    y = pd.DataFrame({"A": 3.0 + 2.0 * x["A"] + rng.normal(0.0, 0.5, n)})

    out = expanding_orthogonalize(y, x, min_obs=MIN_ORTHO_REGRESSION_OBS)

    for t in (MIN_ORTHO_REGRESSION_OBS - 1, 60, 150, n - 1):
        xs = x["A"].to_numpy()[: t + 1]
        ys = y["A"].to_numpy()[: t + 1]
        beta_hat, alpha_hat = np.polyfit(xs, ys, 1)
        expected = ys[-1] - alpha_hat - beta_hat * xs[-1]
        assert out["A"].iloc[t] == pytest.approx(expected, rel=1e-9, abs=1e-12), (
            f"residual at t={t} does not match a hand-fitted OLS on rows 0..{t}"
        )

    assert out["A"].iloc[: MIN_ORTHO_REGRESSION_OBS - 1].isna().all(), (
        "residuals must be NaN before min_obs pairs exist"
    )


def test_perfectly_explained_signal_orthogonalizes_to_zero():
    """If order flow IS an exact affine function of the same-period return,
    there is by construction nothing left after projecting the return out."""
    rng = np.random.default_rng(3)
    x = pd.DataFrame({"A": rng.normal(size=150)})
    y = pd.DataFrame({"A": -7.0 + 4.0 * x["A"]})

    out = expanding_orthogonalize(y, x).dropna()
    assert len(out) > 100
    assert float(out["A"].abs().max()) < 1e-9


def test_orthogonalize_skips_ragged_history_without_injecting_zeros():
    """A coin listed late must not have its pre-listing NaNs counted as
    (0, 0) observations in its own expanding regression."""
    rng = np.random.default_rng(5)
    n = 200
    x = pd.DataFrame({"A": rng.normal(size=n)})
    y = pd.DataFrame({"A": 1.0 + 2.0 * x["A"] + rng.normal(0.0, 0.3, n)})
    x_ragged, y_ragged = x.copy(), y.copy()
    x_ragged.iloc[:50] = np.nan
    y_ragged.iloc[:50] = np.nan

    out = expanding_orthogonalize(y_ragged, x_ragged)

    assert out["A"].iloc[:50].isna().all()
    # first defined residual arrives min_obs valid pairs after the listing
    first_valid = int(out["A"].notna().to_numpy().argmax())
    assert first_valid == 50 + MIN_ORTHO_REGRESSION_OBS - 1

    xs = x_ragged["A"].to_numpy()[50 : first_valid + 1]
    ys = y_ragged["A"].to_numpy()[50 : first_valid + 1]
    beta_hat, alpha_hat = np.polyfit(xs, ys, 1)
    assert out["A"].iloc[first_valid] == pytest.approx(
        ys[-1] - alpha_hat - beta_hat * xs[-1], rel=1e-9
    )


# --- the formula, by hand ----------------------------------------------------


def test_order_flow_log_difference_hand_computed():
    """buy=75, sell=25 -> log(75/25) = log 3. buy=20, sell=80 -> log(1/4)
    = -log 4. Symmetric halves -> exactly 0."""
    buy = pd.DataFrame({"A": [75.0, 20.0, 50.0], "B": [1.0, 1.0, 1.0]})
    sell = pd.DataFrame({"A": [25.0, 80.0, 50.0], "B": [1.0, 1.0, 1.0]})

    of = order_flow_log_difference(buy, sell)

    assert of["A"].iloc[0] == pytest.approx(math.log(3.0))
    assert of["A"].iloc[0] == pytest.approx(1.0986122886681098)
    assert of["A"].iloc[1] == pytest.approx(-math.log(4.0))
    assert of["A"].iloc[2] == pytest.approx(0.0)
    assert (of["B"] == 0.0).all()


def test_order_flow_refuses_non_positive_halves_rather_than_clipping():
    """A bar with no seller-initiated volume has an undefined log ratio; it
    must become NaN, never a huge finite number that would win a leg slot."""
    buy = pd.DataFrame({"A": [10.0, 10.0, 0.0, -1.0]})
    sell = pd.DataFrame({"A": [10.0, 0.0, 10.0, 10.0]})

    of = order_flow_log_difference(buy, sell)

    assert of["A"].iloc[0] == pytest.approx(0.0)
    assert of["A"].iloc[1:].isna().all()


def test_signed_volume_identity_matches_the_provider_contract():
    """The identity the provider verified against the raw tape, restated as
    a test so a future change to either side breaks loudly: seller-initiated
    volume is the residual quote_volume - taker_buy_quote_volume, and the
    resulting flow is the log ratio of the two halves."""
    assert KLINE_COLUMNS == (
        "close",
        "quote_volume",
        "taker_buy_quote_volume",
        "trade_count",
    )
    quote_volume, taker_buy = 42948.692, 33972.7421  # the ADAUSDT bar reconciled live
    sell = quote_volume - taker_buy
    assert sell == pytest.approx(8975.9499, abs=1e-6)

    of = order_flow_log_difference(
        pd.DataFrame({"A": [taker_buy]}), pd.DataFrame({"A": [sell]})
    )
    assert of["A"].iloc[0] == pytest.approx(math.log(taker_buy) - math.log(sell))
    assert of["A"].iloc[0] == pytest.approx(1.3310097329253594, rel=1e-12)


def test_standardization_is_scale_only_not_a_z_score():
    """Equation (1.2) divides by sigma and does NOT subtract a mean. A
    z-score implementation would zero out a constant-mean series' level;
    this one must preserve it, sign included."""
    n = 60
    of = pd.DataFrame({"A": [5.0 + (1.0 if i % 2 else -1.0) for i in range(n)]})

    out = standardize_order_flow(of, window=OFI_STANDARDIZATION_WINDOW)

    sigma = float(of["A"].iloc[:OFI_STANDARDIZATION_WINDOW].std())
    at_first = out["A"].iloc[OFI_STANDARDIZATION_WINDOW - 1]
    assert at_first == pytest.approx(of["A"].iloc[OFI_STANDARDIZATION_WINDOW - 1] / sigma)
    assert at_first > 0.0, "a positive flow must stay positive — demeaning would flip signs"
    assert out["A"].iloc[: OFI_STANDARDIZATION_WINDOW - 1].isna().all()

    demeaned = (of - of.rolling(OFI_STANDARDIZATION_WINDOW).mean()) / of.rolling(
        OFI_STANDARDIZATION_WINDOW
    ).std()
    assert not np.isclose(at_first, demeaned["A"].iloc[OFI_STANDARDIZATION_WINDOW - 1])


def test_standardization_window_is_inclusive_of_the_current_observation():
    """sigma(of_{t-29:t}) is 30 observations ENDING AT t, so the first
    defined value is at row 29, not row 30."""
    of = pd.DataFrame({"A": np.arange(1.0, 41.0)})
    out = standardize_order_flow(of, window=OFI_STANDARDIZATION_WINDOW)
    assert pd.isna(out["A"].iloc[OFI_STANDARDIZATION_WINDOW - 2])
    assert pd.notna(out["A"].iloc[OFI_STANDARDIZATION_WINDOW - 1])


def test_degenerate_sigma_yields_nan_not_infinity():
    of = pd.DataFrame({"A": [2.0] * 40})
    out = standardize_order_flow(of, window=OFI_STANDARDIZATION_WINDOW)
    assert out["A"].isna().all(), "a constant flow has sigma 0 — the ratio must not be inf"


# --- family and grid ---------------------------------------------------------


def test_family_is_exactly_the_predeclared_enumeration():
    specs = build_ofi_family()
    assert len(specs) == OFI_N_TRIALS == 4
    assert {s.pattern_id for s in specs} == {
        "ofi_ortho_h7",
        "ofi_ortho_h1",
        "ofi_raw_h7",
        "ofi_raw_h1",
    }
    assert {s.signal_variant for s in specs} == set(OFI_SIGNAL_VARIANTS)
    assert {s.horizon_days for s in specs} == set(OFI_HORIZON_DAYS)
    assert all(s.rank_fraction == OFI_RANK_FRACTION == 0.2 for s in specs)
    primaries = [s for s in specs if s.is_primary]
    assert [s.pattern_id for s in primaries] == ["ofi_ortho_h7"]


def test_formation_grid_is_non_overlapping_and_leaves_a_full_lookback():
    index = pd.date_range("2020-01-01", periods=40, freq="D")
    rows = formation_grid(index, 7)
    assert rows == [7, 14, 21, 28, 35]
    assert min(rows) >= 7, "the first formation needs a full 7-day window behind it"
    assert all(b - a == 7 for a, b in itertools.pairwise(rows))


def test_weekly_signal_aggregates_the_whole_week_not_just_the_last_day():
    """The horizon-7 flow is the log ratio of the week's SUMMED halves. A
    week whose days individually look balanced but whose totals do not must
    produce a non-zero flow."""
    index = pd.date_range("2020-01-01", periods=30, freq="D")
    buy = pd.DataFrame(100.0, index=index, columns=["A"])
    sell = pd.DataFrame(100.0, index=index, columns=["A"])
    buy.iloc[8:15] = 300.0  # one lopsided week
    close = pd.DataFrame(100.0, index=index, columns=["A"])
    panels = OfiPanels(
        close=close,
        quote_volume=pd.DataFrame(1e9, index=index, columns=["A"]),
        buy_quote=buy,
        sell_quote=sell,
        trade_count=pd.DataFrame(1.0, index=index, columns=["A"]),
        coverage={},
        symbols_missing=[],
    )
    signals = build_ofi_signals(panels, 7)
    rows = formation_grid(index, 7)
    at_14 = rows.index(14)
    of_expected = math.log(300.0 * 7) - math.log(100.0 * 7)
    # standardization is applied on top, so check the pre-standardized ratio
    week_buy = buy["A"].iloc[8:15].sum()
    week_sell = sell["A"].iloc[8:15].sum()
    assert math.log(week_buy) - math.log(week_sell) == pytest.approx(of_expected)
    assert signals.period_return.index[at_14] == index[14]


# --- persistence contract ----------------------------------------------------


def test_screening_results_carry_the_persistence_contract_fields():
    """persist_cross_sectional_trial_results reads .pattern_id (or
    .spec_id), .sharpe_annualized, .n_trading_days and .deflated_sharpe and
    raises on the first one missing — pin them here rather than at the call
    site."""
    panels = _build_world(flow_carries_genuine_info=True, n_days=900)
    config = OfiConfig(cost_bps=0.0, formation_start=date(2020, 1, 1))
    results, daily, reversal = screen_ofi_family(panels, build_ofi_family(), config)

    assert results, "the synthetic world should produce replayable specs"
    for r in results:
        assert isinstance(r.pattern_id, str) and r.pattern_id
        assert isinstance(r.sharpe_annualized, float)
        assert isinstance(r.n_trading_days, int) and r.n_trading_days > 0
        assert r.deflated_sharpe is not None
        assert r.deflated_sharpe.n_trials == OFI_N_TRIALS == 4
        assert np.isfinite(r.sharpe_gross_annualized)
    assert set(daily) == {r.pattern_id for r in results}
    assert set(reversal) == set(OFI_HORIZON_DAYS)


def test_dsr_denominator_is_the_predeclared_size_not_the_survivor_count():
    """Even if a spec drops out of the replay, the DSR must still be
    penalized for all 4 pre-declared trials."""
    panels = _build_world(flow_carries_genuine_info=True, n_days=900)
    config = OfiConfig(cost_bps=0.0, formation_start=date(2020, 1, 1))
    results, _, _ = screen_ofi_family(panels, build_ofi_family(), config)
    assert all(r.deflated_sharpe.n_trials == 4 for r in results)


def test_costs_reduce_the_net_sharpe_and_are_charged_once_per_formation():
    panels = _build_world(flow_carries_genuine_info=True, n_days=600)
    spec = OfiSpec(pattern_id="t", signal_variant="ortho", horizon_days=7)

    free = run_ofi_backtest(panels, spec, OfiConfig(cost_bps=0.0, formation_start=date(2020, 1, 1)))
    charged = run_ofi_backtest(
        panels, spec, OfiConfig(cost_bps=10.0, formation_start=date(2020, 1, 1))
    )

    assert free.total_cost_drag == 0.0
    assert charged.total_cost_drag > 0.0
    pd.testing.assert_series_equal(free.daily_returns_gross, charged.daily_returns_gross)
    assert charged.daily_returns.sum() < free.daily_returns.sum()

    formed = [f for f in charged.formations if f.skipped_reason is None]
    expected = sum(f.turnover for f in charged.formations) * 10.0 / 10_000.0
    assert charged.total_cost_drag == pytest.approx(expected)
    assert len(formed) > 10


def test_thin_universe_skips_the_formation_flat_rather_than_forming_a_partial_book():
    index = pd.date_range("2020-01-01", periods=300, freq="D")
    cols = ["AUSDT", "BUSDT", "CUSDT"]  # far too few for two disjoint quintile legs
    rng = np.random.default_rng(2)
    close = pd.DataFrame(
        100.0 * np.cumprod(1.0 + rng.normal(0, 0.02, (300, 3)), axis=0),
        index=index,
        columns=cols,
    )
    panels = _panels_from_flows(
        pd.DataFrame(rng.normal(0, 1, (300, 3)), index=index, columns=cols), close
    )
    spec = OfiSpec(pattern_id="t", signal_variant="raw", horizon_days=7)
    bt = run_ofi_backtest(panels, spec, OfiConfig(formation_start=date(2020, 1, 1)))

    assert bt.formations, "formations should still be attempted and recorded"
    assert all(f.skipped_reason is not None for f in bt.formations)
    assert all(f.n_long == 0 and f.n_short == 0 for f in bt.formations)
    assert float(bt.daily_returns.abs().sum()) == 0.0, "a skipped formation must sit in cash"


# --- reporting: the uneconomic-signal finding must not be suppressed ---------


def _result(pattern_id: str, *, net: float, gross: float, cum: float, drag: float) -> OfiSpecResult:
    """A minimal OfiSpecResult for exercising the summary text. Only the
    fields the breakeven / uneconomic branches read are meaningful."""
    return OfiSpecResult(
        pattern_id=pattern_id,
        family=OFI_FAMILY_KEY,
        citation="",
        signal_variant="ortho",
        horizon_days=1,
        is_primary=False,
        n_formations=100,
        n_skipped_formations=0,
        avg_names_per_leg=10.0,
        n_trading_days=100,
        sharpe_annualized=net,
        sharpe_gross_annualized=gross,
        mean_return_per_formation=0.0,
        total_cost_drag=drag,
        total_turnover=drag * 1000.0,
        cumulative_net_return=cum,
        reversal_correlation=0.0,
        deflated_sharpe=compute_deflated_sharpe(
            net, pd.Series(np.zeros(100)), OFI_N_TRIALS, None, periods_per_year=365.0
        ),
    )


def _summary_with(results: list[OfiSpecResult]) -> str:
    return _build_summary_text(
        OfiScreeningSummary(
            results=results,
            n_trials=OFI_N_TRIALS,
            periods_per_year=365.0,
            panel_start=date(2020, 1, 1),
            panel_end=date(2026, 1, 1),
            n_panel_rows=2000,
            formation_start=date(2020, 10, 1),
            candidate_universe_size=73,
            symbols_missing=[],
            coverage={},
            min_eligible=25,
            median_eligible=57.0,
            max_eligible=66,
        )
    )


def test_breakeven_is_reported_for_a_spec_whose_gross_is_positive_but_net_is_not():
    """REGRESSION GUARD for a real defect found by the independent
    verification pass: the breakeven line used to be gated on the NET Sharpe
    being positive, which suppressed it for precisely the specs where it is
    the whole point — a strong gross signal whose cost makes it unharvestable.
    That silently deleted this family's most interesting finding from its own
    report. The gate is on the GROSS result now."""
    # gross cumulative = -2.51 + 5.86 = +3.35 -> breakeven 10bp * 3.35/5.86
    uneconomic = _result("ofi_ortho_h1", net=-1.05, gross=1.40, cum=-2.5127, drag=5.8569)
    text = _summary_with([uneconomic])

    assert "breakeven ~5.7bp one-way" in text, text
    assert "STRONG SIGNAL THAT CANNOT PAY THE FEE" in text
    assert f"{BINANCE_TAKER_FEE_BPS:.0f}bp" in text


def test_a_spec_that_loses_money_gross_gets_no_breakeven_line():
    """The other side of the same gate: a breakeven cost is meaningless when
    there is no gross profit to spend, so it must not be invented."""
    text = _summary_with([_result("ofi_x", net=-2.0, gross=-1.5, cum=-3.0, drag=1.0)])

    # "breakevens below" appears in the standing COSTS preamble; what must be
    # absent is a computed per-spec breakeven for THIS spec.
    assert "breakeven ~" not in text
    assert "CANNOT PAY THE FEE" not in text


def test_the_published_binance_taker_fee_is_recorded_as_the_floor_not_the_charge():
    """The specs are charged OFI_COST_BPS, deliberately above the exchange's
    headline taker fee. The fee constant exists only to give the breakeven a
    floor to be compared against, and must never quietly become the charge."""
    assert BINANCE_TAKER_FEE_BPS == 5.0
    assert OFI_COST_BPS == 10.0
    assert OFI_COST_BPS > BINANCE_TAKER_FEE_BPS
