"""add forward validation registrations table

Revision ID: 3107457b11f3
Revises: 2c27def43df8
Create Date: 2026-08-23 13:41:11.624330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3107457b11f3'
down_revision: Union[str, Sequence[str], None] = '2c27def43df8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forward_validation_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('strategy_name', sa.String(length=50), nullable=False),
    sa.Column('ticker_a', sa.String(length=10), nullable=False),
    sa.Column('ticker_b', sa.String(length=10), nullable=False),
    sa.Column('fit_window_days', sa.Integer(), nullable=False),
    sa.Column('entry_z', sa.Float(), nullable=False),
    sa.Column('exit_z', sa.Float(), nullable=False),
    sa.Column('cost_bps', sa.Float(), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('min_trading_days_threshold', sa.Integer(), nullable=False),
    sa.Column('n_forward_trading_days', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.Date(), nullable=False),
    sa.Column('last_processed_date', sa.Date(), nullable=True),
    sa.Column('last_ticked_at', sa.DateTime(), nullable=True),
    sa.Column('graduated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('carry_state_json', sa.Text(), nullable=False),
    sa.Column('day_results_json', sa.Text(), nullable=False),
    sa.Column('trades_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'config_hash', name='uq_forward_validation_user_config')
    )
    op.create_index(op.f('ix_forward_validation_registrations_status'), 'forward_validation_registrations', ['status'], unique=False)
    op.create_index(op.f('ix_forward_validation_registrations_strategy_name'), 'forward_validation_registrations', ['strategy_name'], unique=False)
    op.create_index(op.f('ix_forward_validation_registrations_ticker_a'), 'forward_validation_registrations', ['ticker_a'], unique=False)
    op.create_index(op.f('ix_forward_validation_registrations_ticker_b'), 'forward_validation_registrations', ['ticker_b'], unique=False)
    op.create_index(op.f('ix_forward_validation_registrations_user_id'), 'forward_validation_registrations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forward_validation_registrations_user_id'), table_name='forward_validation_registrations')
    op.drop_index(op.f('ix_forward_validation_registrations_ticker_b'), table_name='forward_validation_registrations')
    op.drop_index(op.f('ix_forward_validation_registrations_ticker_a'), table_name='forward_validation_registrations')
    op.drop_index(op.f('ix_forward_validation_registrations_strategy_name'), table_name='forward_validation_registrations')
    op.drop_index(op.f('ix_forward_validation_registrations_status'), table_name='forward_validation_registrations')
    op.drop_table('forward_validation_registrations')
    # ### end Alembic commands ###
