"""add regime column to screening_candidates

Revision ID: 7a59e4b33aba
Revises: b5f9850987cf
Create Date: 2026-08-24 14:27:21.924377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a59e4b33aba'
down_revision: Union[str, Sequence[str], None] = 'b5f9850987cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screening_candidates', sa.Column('regime', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screening_candidates', 'regime')
    # ### end Alembic commands ###
