"""add stock fundamentals table

Revision ID: 80b5c3afc051
Revises: 6e17e2e70f23
Create Date: 2026-08-22 22:20:53.107928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80b5c3afc051'
down_revision: Union[str, Sequence[str], None] = '6e17e2e70f23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_fundamentals',
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('exchange', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('ipo_date', sa.String(length=10), nullable=True),
    sa.Column('market_capitalization', sa.Float(), nullable=True),
    sa.Column('share_outstanding', sa.Float(), nullable=True),
    sa.Column('finnhub_industry', sa.String(length=100), nullable=True),
    sa.Column('weburl', sa.String(length=300), nullable=True),
    sa.Column('logo', sa.String(length=300), nullable=True),
    sa.Column('week52_high', sa.Float(), nullable=True),
    sa.Column('week52_low', sa.Float(), nullable=True),
    sa.Column('beta', sa.Float(), nullable=True),
    sa.Column('pe_ttm', sa.Float(), nullable=True),
    sa.Column('eps_ttm', sa.Float(), nullable=True),
    sa.Column('roe_ttm', sa.Float(), nullable=True),
    sa.Column('roa_ttm', sa.Float(), nullable=True),
    sa.Column('gross_margin_ttm', sa.Float(), nullable=True),
    sa.Column('net_margin_ttm', sa.Float(), nullable=True),
    sa.Column('current_ratio', sa.Float(), nullable=True),
    sa.Column('quick_ratio', sa.Float(), nullable=True),
    sa.Column('debt_to_equity', sa.Float(), nullable=True),
    sa.Column('dividend_yield_ttm', sa.Float(), nullable=True),
    sa.Column('avg_10day_volume', sa.Float(), nullable=True),
    sa.Column('recommendation_trend_json', sa.Text(), nullable=True),
    sa.Column('peers_json', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_fundamentals')
    # ### end Alembic commands ###
