"""add macro observations table

Revision ID: cbffd3fa57df
Revises: fe9ec946c496
Create Date: 2026-08-22 16:53:45.896405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbffd3fa57df'
down_revision: Union[str, Sequence[str], None] = 'fe9ec946c496'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('macro_observations',
    sa.Column('series_id', sa.String(length=30), nullable=False),
    sa.Column('observation_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('series_id', 'observation_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('macro_observations')
    # ### end Alembic commands ###
