"""add hac_significant and regime_hmm to screening_candidates

Revision ID: f7afb72c016d
Revises: b96020d21d90
Create Date: 2026-08-25 05:41:32.143551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7afb72c016d'
down_revision: Union[str, Sequence[str], None] = 'b96020d21d90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screening_candidates', sa.Column('hac_significant', sa.Boolean(), nullable=True))
    op.add_column('screening_candidates', sa.Column('regime_hmm', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screening_candidates', 'regime_hmm')
    op.drop_column('screening_candidates', 'hac_significant')
    # ### end Alembic commands ###
