"""add is_verified and user_tokens

Revision ID: fe9ec946c496
Revises: fd5499dd55da
Create Date: 2026-08-22 14:49:27.984146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe9ec946c496'
down_revision: Union[str, Sequence[str], None] = 'fd5499dd55da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_tokens_token_hash'), 'user_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_user_tokens_user_id'), 'user_tokens', ['user_id'], unique=False)
    # Existing users (real accounts already created before this feature
    # shipped, on both local SQLite and production Postgres) predate
    # mandatory verification — backfilling to True avoids retroactively
    # locking out working accounts. sa.true() (not a raw 1/true literal)
    # compiles correctly on both dialects; Postgres does not implicitly
    # cast an integer default to boolean. New rows always pass
    # is_verified=False explicitly from the ORM, so this default only
    # ever matters for this one-time backfill.
    op.add_column(
        'users', sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.true())
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_tokens_user_id'), table_name='user_tokens')
    op.drop_index(op.f('ix_user_tokens_token_hash'), table_name='user_tokens')
    op.drop_table('user_tokens')
    # SQLite has no ALTER COLUMN/DROP COLUMN — batch mode sidesteps that
    # entirely and is a no-op-equivalent on Postgres.
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_column('is_verified')
    # ### end Alembic commands ###
